name: Submit Quiz Score
on:
  repository_dispatch:
    types: [submit_score]

# Critical permission for public_repo tokens
permissions:
  issues: write  # Only allows creating issues

jobs:
  submit-score:
    runs-on: ubuntu-latest
    steps:
      - name: Submit score
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -X POST \
            -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/issues \
            -d '{
              "title":"${{ github.event.client_payload.username }} - ${{ github.event.client_payload.score }}",
              "body":"Quiz score submission"
            }'
